package vistas;

import conexionDB.Conexion;
import java.sql.*;

/**
 *
 * @author kevindominguez
 */
public class Inicio extends javax.swing.JFrame {

    private final javax.swing.border.Border PADDING_FIELD = javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3);
    private final javax.swing.border.Border BORDERLINE_FIELD = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153));
    private final javax.swing.border.Border BORDER = javax.swing.BorderFactory.createCompoundBorder(BORDERLINE_FIELD, PADDING_FIELD);
    private final javax.swing.border.Border BORDERLINE_FIELD_EXCEPTION = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0));
    private final javax.swing.border.Border BORDER_EXCEPTION = javax.swing.BorderFactory.createCompoundBorder(BORDERLINE_FIELD_EXCEPTION, PADDING_FIELD);
    private final String DATOS_INCORRECTOS = "Usuario o contraseña incorrectos";
    private final String CAMPOS_VACIOS = "Rellene los campos vacíos";

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jlPlaceholderUsuario = new javax.swing.JLabel();
        jlPlaceholderContraseña = new javax.swing.JLabel();
        jlTitle = new javax.swing.JLabel();
        jlTittle = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jpfContraseña = new javax.swing.JPasswordField();
        jlExcepcion = new javax.swing.JLabel();
        jbInicio = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(731, 409));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 392));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlPlaceholderUsuario.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        jlPlaceholderUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jlPlaceholderUsuario.setText(" Usuario");
        jPanel2.add(jlPlaceholderUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 193, 190, 40));

        jlPlaceholderContraseña.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        jlPlaceholderContraseña.setForeground(new java.awt.Color(204, 204, 204));
        jlPlaceholderContraseña.setText(" Contraseña");
        jPanel2.add(jlPlaceholderContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 230, 70));

        jlTitle.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jlTitle.setText("Bienvenido");
        jPanel2.add(jlTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jlTittle.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jlTittle.setForeground(new java.awt.Color(102, 255, 255));
        jlTittle.setText("Paletero");
        jPanel2.add(jlTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jtfUsuario.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        jtfUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jtfUsuario.setBorder(BORDER);
        jtfUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfUsuarioKeyReleased(evt);
            }
        });
        jPanel2.add(jtfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 240, 40));

        jpfContraseña.setBorder(BORDER);
        jpfContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfContraseñaActionPerformed(evt);
            }
        });
        jpfContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpfContraseñaKeyReleased(evt);
            }
        });
        jPanel2.add(jpfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 250, 40));

        jlExcepcion.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(jlExcepcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, 20));
        jlExcepcion.setVisible(false);

        jbInicio.setBackground(new java.awt.Color(255, 255, 255));
        jbInicio.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jbInicio.setText("Iniciar Sesión");
        jbInicio.setBorderPainted(false);
        jbInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInicioActionPerformed(evt);
            }
        });
        jPanel2.add(jbInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 440, 550));

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));

        jLabel3.setFont(new java.awt.Font("Open Sans Semibold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("venta");

        jLabel4.setFont(new java.awt.Font("Open Sans Semibold", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sistema punto de");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(423, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInicioActionPerformed
        String username = jtfUsuario.getText().trim();
        char password[] = jpfContraseña.getPassword();
        byte flujo = 0;

        if (username.isEmpty()) {
            flujo += 1;
        }
        if (password.length == 0) {
            flujo += 2;
        }

        if (flujo > 0) {
            jlExcepcion.setText(CAMPOS_VACIOS);
            jlExcepcion.setVisible(true);

            switch (flujo) {
                case 1:
                    jtfUsuario.setBorder(BORDER_EXCEPTION);
                    break;
                case 2:
                    jpfContraseña.setBorder(BORDER_EXCEPTION);
                    break;
                case 3: {
                    jtfUsuario.setBorder(BORDER_EXCEPTION);
                    jpfContraseña.setBorder(BORDER_EXCEPTION);
                }
                break;
            }
            return;
        }

        try {
            Conexion consulta = new Conexion();
            PreparedStatement pst = consulta.connection.prepareStatement("SELECT * FROM usuario WHERE uUsuario = ? ");
            pst.setString(1, username);
            ResultSet rs = pst.executeQuery();

            if (!rs.next()) {
                jlExcepcion.setText(DATOS_INCORRECTOS);
                jlExcepcion.setVisible(true);
                return;
            }

            String realPassword = rs.getString("uContraseña");

            for (int i = 0; i < password.length; i++) {
                if (password[i] != realPassword.charAt(i)) {
                    jlExcepcion.setText(DATOS_INCORRECTOS);
                    jlExcepcion.setVisible(true);
                    return;
                }
            }

            System.out.println("CORRECTO");//REDIRIGIR AL CASO DE USO DE CADA UNO
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
            this.dispose();

        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jbInicioActionPerformed

    private void jtfUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfUsuarioKeyReleased
        jlPlaceholderUsuario.setVisible(false);
        jtfUsuario.setBorder(BORDER);
        jlExcepcion.setVisible(false);
    }//GEN-LAST:event_jtfUsuarioKeyReleased

    private void jpfContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfContraseñaKeyReleased
        jlPlaceholderContraseña.setVisible(false);
        jpfContraseña.setBorder(BORDER);
        jlExcepcion.setVisible(false);
    }//GEN-LAST:event_jpfContraseñaKeyReleased

    private void jpfContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbInicio;
    private javax.swing.JLabel jlExcepcion;
    private javax.swing.JLabel jlPlaceholderContraseña;
    private javax.swing.JLabel jlPlaceholderUsuario;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JLabel jlTittle;
    private javax.swing.JPasswordField jpfContraseña;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
